### ISSUE TITLE
transfer ownership

### ISSUE THREAD

**Issue by gijzelaerr** [fkarb/sqlalchemy-monetdb#3]
Hi!

Can you maybe transfer ownership of this repo to:

https://github.com/gijzelaerr/sqlalchemy-monetdb

if you google now on sqlalchemy monetdb you get your githup repo first. I'm afraid people will use it, and it is quite outdated - probably doesn't even work with recent SQLAlchemy.

greetings,
- Gijs

**Comment by mikewilliamson** [comment]
Hi Gijs,

I don't think that's necessary.  This repository holds the history of the work that Renshaw Bay did on the sqlalchemy-monetdb module, and although it's outdated now we might bring it up to date and make further revisions to it in the future.  I think it's pretty clear by looking at the GitHub network graph that your repository has the most recent changes.  

And anyway, when I did a Google search on "sqlalchemy monetdb" just now it actually came up with your repository first, so I don't think there's much risk of confusion.

Cheers,

-Mike

**Comment by gijzelaerr** [comment]
ok sure. But note that i'm about to fix some issues with the latest sqlalchemy. Since you want to invest time, maybe we should coordinate the effort ? What are you going to work on?

First thing I want to do is let the sqlalchemy test suite pass again.

**Comment by mikewilliamson** [comment]
Hi Gijs,

I’m afraid we don’t have the time to do any work on it in the immediate future.  We’ll probably pick it up when we do our next MonetDB upgrade later in the year.  But thanks for your efforts on the project.  Agreed that getting it to pass the test suite would be a good step forward.

Cheers,

-Mike
